package com.reverseHibernate;
// Generated Sep 14, 2018 12:41:13 PM by Hibernate Tools 5.2.3.Final

/**
 * Department generated by hbm2java
 */
public class Department implements java.io.Serializable {

	private Integer id;
	private Employee employee;
	private String name;

	public Department() {
	}

	public Department(Employee employee, String name) {
		this.employee = employee;
		this.name = name;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Employee getEmployee() {
		return this.employee;
	}

	public void setEmployee(Employee employee) {
		this.employee = employee;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
