package com.reverseHibernate;
// Generated Sep 14, 2018 12:41:13 PM by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;

/**
 * House generated by hbm2java
 */
public class House implements java.io.Serializable {

	private Integer id;
	private String name;
	private Set owners = new HashSet(0);

	public House() {
	}

	public House(String name, Set owners) {
		this.name = name;
		this.owners = owners;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set getOwners() {
		return this.owners;
	}

	public void setOwners(Set owners) {
		this.owners = owners;
	}

}
