package com.reverseHibernate;
// Generated Sep 14, 2018 12:41:13 PM by Hibernate Tools 5.2.3.Final

/**
 * Owner generated by hbm2java
 */
public class Owner implements java.io.Serializable {

	private Integer id;
	private House house;
	private String name;
	private Integer houserent;

	public Owner() {
	}

	public Owner(House house) {
		this.house = house;
	}

	public Owner(House house, String name, Integer houserent) {
		this.house = house;
		this.name = name;
		this.houserent = houserent;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public House getHouse() {
		return this.house;
	}

	public void setHouse(House house) {
		this.house = house;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Integer getHouserent() {
		return this.houserent;
	}

	public void setHouserent(Integer houserent) {
		this.houserent = houserent;
	}

}
