package com.reverseHibernate;
// Generated Sep 14, 2018 12:41:13 PM by Hibernate Tools 5.2.3.Final

/**
 * Product generated by hbm2java
 */
public class Product implements java.io.Serializable {

	private int id;
	private String firstname;
	private String lastname;

	public Product() {
	}

	public Product(int id) {
		this.id = id;
	}

	public Product(int id, String firstname, String lastname) {
		this.id = id;
		this.firstname = firstname;
		this.lastname = lastname;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getFirstname() {
		return this.firstname;
	}

	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}

	public String getLastname() {
		return this.lastname;
	}

	public void setLastname(String lastname) {
		this.lastname = lastname;
	}

}
