package com.reverseHibernate;
// Generated Sep 14, 2018 12:08:49 PM by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Artist generated by hbm2java
 */
public class Artist implements java.io.Serializable {

	private int artistId;
	private String artistName;
	private Set songsForPersonDummy = new HashSet(0);
	private Set songsForForevenId = new HashSet(0);

	public Artist() {
	}

	public Artist(int artistId) {
		this.artistId = artistId;
	}

	public Artist(int artistId, String artistName, Set songsForPersonDummy, Set songsForForevenId) {
		this.artistId = artistId;
		this.artistName = artistName;
		this.songsForPersonDummy = songsForPersonDummy;
		this.songsForForevenId = songsForForevenId;
	}

	public int getArtistId() {
		return this.artistId;
	}

	public void setArtistId(int artistId) {
		this.artistId = artistId;
	}

	public String getArtistName() {
		return this.artistName;
	}

	public void setArtistName(String artistName) {
		this.artistName = artistName;
	}

	public Set getSongsForPersonDummy() {
		return this.songsForPersonDummy;
	}

	public void setSongsForPersonDummy(Set songsForPersonDummy) {
		this.songsForPersonDummy = songsForPersonDummy;
	}

	public Set getSongsForForevenId() {
		return this.songsForForevenId;
	}

	public void setSongsForForevenId(Set songsForForevenId) {
		this.songsForForevenId = songsForForevenId;
	}

}
