package com.reverseHibernate;
// Generated Sep 14, 2018 12:08:49 PM by Hibernate Tools 5.2.3.Final

/**
 * Class generated by hbm2java
 */
public class Class implements java.io.Serializable {

	private int cid;
	private String cname;

	public Class() {
	}

	public Class(int cid) {
		this.cid = cid;
	}

	public Class(int cid, String cname) {
		this.cid = cid;
		this.cname = cname;
	}

	public int getCid() {
		return this.cid;
	}

	public void setCid(int cid) {
		this.cid = cid;
	}

	public String getCname() {
		return this.cname;
	}

	public void setCname(String cname) {
		this.cname = cname;
	}

}
