package com.reverseHibernate;
// Generated Sep 14, 2018 12:08:49 PM by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Department generated by hbm2java
 */
public class Department implements java.io.Serializable {

	private int did;
	private String dname;
	private Set professorsForForevenId = new HashSet(0);
	private Set professorsForDdummy = new HashSet(0);

	public Department() {
	}

	public Department(int did) {
		this.did = did;
	}

	public Department(int did, String dname, Set professorsForForevenId, Set professorsForDdummy) {
		this.did = did;
		this.dname = dname;
		this.professorsForForevenId = professorsForForevenId;
		this.professorsForDdummy = professorsForDdummy;
	}

	public int getDid() {
		return this.did;
	}

	public void setDid(int did) {
		this.did = did;
	}

	public String getDname() {
		return this.dname;
	}

	public void setDname(String dname) {
		this.dname = dname;
	}

	public Set getProfessorsForForevenId() {
		return this.professorsForForevenId;
	}

	public void setProfessorsForForevenId(Set professorsForForevenId) {
		this.professorsForForevenId = professorsForForevenId;
	}

	public Set getProfessorsForDdummy() {
		return this.professorsForDdummy;
	}

	public void setProfessorsForDdummy(Set professorsForDdummy) {
		this.professorsForDdummy = professorsForDdummy;
	}

}
