package com.reverseHibernate;
// Generated Sep 14, 2018 12:08:49 PM by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Director generated by hbm2java
 */
public class Director implements java.io.Serializable {

	private int directorId;
	private String directorName;
	private Set moviesForForevenId = new HashSet(0);
	private Set moviesForPersonDummy = new HashSet(0);

	public Director() {
	}

	public Director(int directorId) {
		this.directorId = directorId;
	}

	public Director(int directorId, String directorName, Set moviesForForevenId, Set moviesForPersonDummy) {
		this.directorId = directorId;
		this.directorName = directorName;
		this.moviesForForevenId = moviesForForevenId;
		this.moviesForPersonDummy = moviesForPersonDummy;
	}

	public int getDirectorId() {
		return this.directorId;
	}

	public void setDirectorId(int directorId) {
		this.directorId = directorId;
	}

	public String getDirectorName() {
		return this.directorName;
	}

	public void setDirectorName(String directorName) {
		this.directorName = directorName;
	}

	public Set getMoviesForForevenId() {
		return this.moviesForForevenId;
	}

	public void setMoviesForForevenId(Set moviesForForevenId) {
		this.moviesForForevenId = moviesForForevenId;
	}

	public Set getMoviesForPersonDummy() {
		return this.moviesForPersonDummy;
	}

	public void setMoviesForPersonDummy(Set moviesForPersonDummy) {
		this.moviesForPersonDummy = moviesForPersonDummy;
	}

}
