package com.reverseHibernate;
// Generated Sep 14, 2018 12:08:49 PM by Hibernate Tools 5.2.3.Final

/**
 * Lecture generated by hbm2java
 */
public class Lecture implements java.io.Serializable {

	private int lid;
	private Course course;
	private String lname;

	public Lecture() {
	}

	public Lecture(int lid) {
		this.lid = lid;
	}

	public Lecture(int lid, Course course, String lname) {
		this.lid = lid;
		this.course = course;
		this.lname = lname;
	}

	public int getLid() {
		return this.lid;
	}

	public void setLid(int lid) {
		this.lid = lid;
	}

	public Course getCourse() {
		return this.course;
	}

	public void setCourse(Course course) {
		this.course = course;
	}

	public String getLname() {
		return this.lname;
	}

	public void setLname(String lname) {
		this.lname = lname;
	}

}
