package com.reverseHibernate;
// Generated Sep 14, 2018 12:08:49 PM by Hibernate Tools 5.2.3.Final

/**
 * Medication generated by hbm2java
 */
public class Medication implements java.io.Serializable {

	private int medicationId;
	private Person person;
	private String medicationName;

	public Medication() {
	}

	public Medication(int medicationId) {
		this.medicationId = medicationId;
	}

	public Medication(int medicationId, Person person, String medicationName) {
		this.medicationId = medicationId;
		this.person = person;
		this.medicationName = medicationName;
	}

	public int getMedicationId() {
		return this.medicationId;
	}

	public void setMedicationId(int medicationId) {
		this.medicationId = medicationId;
	}

	public Person getPerson() {
		return this.person;
	}

	public void setPerson(Person person) {
		this.person = person;
	}

	public String getMedicationName() {
		return this.medicationName;
	}

	public void setMedicationName(String medicationName) {
		this.medicationName = medicationName;
	}

}
