package com.reverseHibernate;
// Generated Sep 14, 2018 12:08:49 PM by Hibernate Tools 5.2.3.Final

/**
 * Movie generated by hbm2java
 */
public class Movie implements java.io.Serializable {

	private int movieId;
	private Director directorByForevenId;
	private Director directorByPersonDummy;
	private String movieName;

	public Movie() {
	}

	public Movie(int movieId) {
		this.movieId = movieId;
	}

	public Movie(int movieId, Director directorByForevenId, Director directorByPersonDummy, String movieName) {
		this.movieId = movieId;
		this.directorByForevenId = directorByForevenId;
		this.directorByPersonDummy = directorByPersonDummy;
		this.movieName = movieName;
	}

	public int getMovieId() {
		return this.movieId;
	}

	public void setMovieId(int movieId) {
		this.movieId = movieId;
	}

	public Director getDirectorByForevenId() {
		return this.directorByForevenId;
	}

	public void setDirectorByForevenId(Director directorByForevenId) {
		this.directorByForevenId = directorByForevenId;
	}

	public Director getDirectorByPersonDummy() {
		return this.directorByPersonDummy;
	}

	public void setDirectorByPersonDummy(Director directorByPersonDummy) {
		this.directorByPersonDummy = directorByPersonDummy;
	}

	public String getMovieName() {
		return this.movieName;
	}

	public void setMovieName(String movieName) {
		this.movieName = movieName;
	}

}
