package com.reverseHibernate;
// Generated Sep 14, 2018 12:08:49 PM by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Person generated by hbm2java
 */
public class Person implements java.io.Serializable {

	private int personId;
	private String personName;
	private Set medications = new HashSet(0);

	public Person() {
	}

	public Person(int personId) {
		this.personId = personId;
	}

	public Person(int personId, String personName, Set medications) {
		this.personId = personId;
		this.personName = personName;
		this.medications = medications;
	}

	public int getPersonId() {
		return this.personId;
	}

	public void setPersonId(int personId) {
		this.personId = personId;
	}

	public String getPersonName() {
		return this.personName;
	}

	public void setPersonName(String personName) {
		this.personName = personName;
	}

	public Set getMedications() {
		return this.medications;
	}

	public void setMedications(Set medications) {
		this.medications = medications;
	}

}
