package com.reverseHibernate;
// Generated Sep 14, 2018 12:08:49 PM by Hibernate Tools 5.2.3.Final

/**
 * Professor generated by hbm2java
 */
public class Professor implements java.io.Serializable {

	private int pid;
	private Department departmentByForevenId;
	private Department departmentByDdummy;
	private String pname;

	public Professor() {
	}

	public Professor(int pid) {
		this.pid = pid;
	}

	public Professor(int pid, Department departmentByForevenId, Department departmentByDdummy, String pname) {
		this.pid = pid;
		this.departmentByForevenId = departmentByForevenId;
		this.departmentByDdummy = departmentByDdummy;
		this.pname = pname;
	}

	public int getPid() {
		return this.pid;
	}

	public void setPid(int pid) {
		this.pid = pid;
	}

	public Department getDepartmentByForevenId() {
		return this.departmentByForevenId;
	}

	public void setDepartmentByForevenId(Department departmentByForevenId) {
		this.departmentByForevenId = departmentByForevenId;
	}

	public Department getDepartmentByDdummy() {
		return this.departmentByDdummy;
	}

	public void setDepartmentByDdummy(Department departmentByDdummy) {
		this.departmentByDdummy = departmentByDdummy;
	}

	public String getPname() {
		return this.pname;
	}

	public void setPname(String pname) {
		this.pname = pname;
	}

}
