package com.reverseHibernate;
// Generated Sep 14, 2018 12:08:49 PM by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Project generated by hbm2java
 */
public class Project implements java.io.Serializable {

	private int projectId;
	private String contactName;
	private Set stakeholders = new HashSet(0);

	public Project() {
	}

	public Project(int projectId) {
		this.projectId = projectId;
	}

	public Project(int projectId, String contactName, Set stakeholders) {
		this.projectId = projectId;
		this.contactName = contactName;
		this.stakeholders = stakeholders;
	}

	public int getProjectId() {
		return this.projectId;
	}

	public void setProjectId(int projectId) {
		this.projectId = projectId;
	}

	public String getContactName() {
		return this.contactName;
	}

	public void setContactName(String contactName) {
		this.contactName = contactName;
	}

	public Set getStakeholders() {
		return this.stakeholders;
	}

	public void setStakeholders(Set stakeholders) {
		this.stakeholders = stakeholders;
	}

}
