package com.reverseHibernate;
// Generated Sep 14, 2018 12:08:49 PM by Hibernate Tools 5.2.3.Final

/**
 * Song generated by hbm2java
 */
public class Song implements java.io.Serializable {

	private int songId;
	private Artist artistByPersonDummy;
	private Artist artistByForevenId;
	private String songName;

	public Song() {
	}

	public Song(int songId) {
		this.songId = songId;
	}

	public Song(int songId, Artist artistByPersonDummy, Artist artistByForevenId, String songName) {
		this.songId = songId;
		this.artistByPersonDummy = artistByPersonDummy;
		this.artistByForevenId = artistByForevenId;
		this.songName = songName;
	}

	public int getSongId() {
		return this.songId;
	}

	public void setSongId(int songId) {
		this.songId = songId;
	}

	public Artist getArtistByPersonDummy() {
		return this.artistByPersonDummy;
	}

	public void setArtistByPersonDummy(Artist artistByPersonDummy) {
		this.artistByPersonDummy = artistByPersonDummy;
	}

	public Artist getArtistByForevenId() {
		return this.artistByForevenId;
	}

	public void setArtistByForevenId(Artist artistByForevenId) {
		this.artistByForevenId = artistByForevenId;
	}

	public String getSongName() {
		return this.songName;
	}

	public void setSongName(String songName) {
		this.songName = songName;
	}

}
