package com.reverseHibernate;
// Generated Sep 14, 2018 12:06:35 PM by Hibernate Tools 5.2.3.Final

/**
 * Student generated by hbm2java
 */
public class Student implements java.io.Serializable {

	private int sid;
	private String sname;

	public Student() {
	}

	public Student(int sid) {
		this.sid = sid;
	}

	public Student(int sid, String sname) {
		this.sid = sid;
		this.sname = sname;
	}

	public int getSid() {
		return this.sid;
	}

	public void setSid(int sid) {
		this.sid = sid;
	}

	public String getSname() {
		return this.sname;
	}

	public void setSname(String sname) {
		this.sname = sname;
	}

}
