package com.reverseHibernate;
// Generated Sep 14, 2018 12:06:35 PM by Hibernate Tools 5.2.3.Final

/**
 * Switch generated by hbm2java
 */
public class Switch implements java.io.Serializable {

	private int sid;
	private Electroniccomponent electroniccomponentByForevenId;
	private Electroniccomponent electroniccomponentByEdummy;
	private String sname;

	public Switch() {
	}

	public Switch(int sid) {
		this.sid = sid;
	}

	public Switch(int sid, Electroniccomponent electroniccomponentByForevenId,
			Electroniccomponent electroniccomponentByEdummy, String sname) {
		this.sid = sid;
		this.electroniccomponentByForevenId = electroniccomponentByForevenId;
		this.electroniccomponentByEdummy = electroniccomponentByEdummy;
		this.sname = sname;
	}

	public int getSid() {
		return this.sid;
	}

	public void setSid(int sid) {
		this.sid = sid;
	}

	public Electroniccomponent getElectroniccomponentByForevenId() {
		return this.electroniccomponentByForevenId;
	}

	public void setElectroniccomponentByForevenId(Electroniccomponent electroniccomponentByForevenId) {
		this.electroniccomponentByForevenId = electroniccomponentByForevenId;
	}

	public Electroniccomponent getElectroniccomponentByEdummy() {
		return this.electroniccomponentByEdummy;
	}

	public void setElectroniccomponentByEdummy(Electroniccomponent electroniccomponentByEdummy) {
		this.electroniccomponentByEdummy = electroniccomponentByEdummy;
	}

	public String getSname() {
		return this.sname;
	}

	public void setSname(String sname) {
		this.sname = sname;
	}

}
