package com.reverseHibernate;
// Generated Sep 14, 2018 10:55:54 AM by Hibernate Tools 5.2.3.Final

/**
 * Student generated by hbm2java
 */
public class Student implements java.io.Serializable {

	private Integer id;
	private Address address;
	private String name;
	private Integer age;

	public Student() {
	}

	public Student(Address address) {
		this.address = address;
	}

	public Student(Address address, String name, Integer age) {
		this.address = address;
		this.name = name;
		this.age = age;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Address getAddress() {
		return this.address;
	}

	public void setAddress(Address address) {
		this.address = address;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Integer getAge() {
		return this.age;
	}

	public void setAge(Integer age) {
		this.age = age;
	}

}
